# -*- coding: utf-8 -*-
"""gru_arch.png

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-Uasy9oS_LNyMBuLLW9HiQKeskbfohb
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches

fig, ax = plt.subplots(figsize=(10, 5))

# Warstwa wejściowa
ax.add_patch(patches.Rectangle((0.1, 0.4), 0.15, 0.2, edgecolor='black', facecolor='lightgray'))
ax.text(0.175, 0.5, 'Input', ha='center', va='center')

# Warstwa osadzeń
ax.add_patch(patches.Rectangle((0.3, 0.4), 0.15, 0.2, edgecolor='black', facecolor='skyblue'))
ax.text(0.375, 0.5, 'Embedding', ha='center', va='center')

# Warstwa GRU
ax.add_patch(patches.Rectangle((0.5, 0.4), 0.15, 0.2, edgecolor='black', facecolor='lightgreen'))
ax.text(0.575, 0.5, 'GRU', ha='center', va='center')

# Warstwa wyjściowa
ax.add_patch(patches.Rectangle((0.7, 0.4), 0.15, 0.2, edgecolor='black', facecolor='orange'))
ax.text(0.775, 0.5, 'Dense\n(sigmoid)', ha='center', va='center')

# Strzałki
for start, end in [(0.25, 0.375), (0.45, 0.575), (0.65, 0.775)]:
    ax.annotate('', xy=(end, 0.5), xytext=(start, 0.5),
                arrowprops=dict(facecolor='black', arrowstyle='->'))

# Ustawienia wykresu
ax.axis('off')
plt.tight_layout()
plt.savefig('gru_arch.png')
plt.show()