# -*- coding: utf-8 -*-
"""loss_plot.png

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-Uasy9oS_LNyMBuLLW9HiQKeskbfohb
"""

import matplotlib.pyplot as plt

# Przykładowe dane straty (loss) dla 10 epok
epochs = list(range(1, 11))
loss = [1.15, 1.05, 0.95, 0.89, 0.83, 0.79, 0.75, 0.72, 0.71, 0.70]

# Tworzenie wykresu
plt.figure(figsize=(8, 5))
plt.plot(epochs, loss, marker='o', linestyle='-', color='red')
plt.title('Wartość funkcji straty (loss) podczas treningu')
plt.xlabel('Epoka')
plt.ylabel('Funkcja straty (Loss)')
plt.grid(True)
plt.tight_layout()

# Zapis do pliku
plt.savefig('loss_plot.png')
plt.show()